apiVersion: gedgemig.gedge.etri.kr/v1
kind: Livmigration
metadata:
  name: checkpoint-{migration_id}
  namespace: {namespace}
  labels:
    name: checkpoint-{migration_id}
spec:
  replicas: 0
  operation: checkpoint
  snapshotPath: /mnt/migrate/{local_cluster}
  sourcePod: {source_pod}
  selector:
    migPod:
